# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-08 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0002_auto_20190807_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='status',
            field=models.IntegerField(choices=[(1, '以刷'), (0, '未刷'), (2, '不筛选')], verbose_name='审核状态'),
        ),
    ]
