# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-08 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0003_auto_20190808_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='status',
            field=models.BooleanField(default=True, verbose_name='审核状态'),
        ),
    ]
